/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./blog/**/*.html",
    "./presentations/**/*.html",
    "./js/*.js",
    "./_layouts/**/*.html",
    "./_includes/**/*.html",
    "./_posts/**/*.md"
  ],
  theme: {
    extend: {
      colors: {
        // Legacy aliases mapped to Material 3 tokens for backward compatibility
        primary: '#0B57D0',
        secondary: '#1D1B20',
        textColor: '#1D1B20',
        lightGray: '#FEF7FF',
        borderColor: '#CAC4D0',
        highlight: '#0B57D0',
        github: '#1D1B20',
        githubHover: '#322F35',

        // Material 3 light scheme
        'md-primary': '#0B57D0',
        'md-on-primary': '#FFFFFF',
        'md-primary-container': '#D3E3FD',
        'md-on-primary-container': '#001D35',
        'md-secondary': '#00639B',
        'md-on-secondary': '#FFFFFF',
        'md-secondary-container': '#CFE5FF',
        'md-on-secondary-container': '#001D33',
        'md-tertiary': '#6750A4',
        'md-on-tertiary': '#FFFFFF',
        'md-tertiary-container': '#EADDFF',
        'md-on-tertiary-container': '#21005D',
        'md-error': '#B3261E',
        'md-on-error': '#FFFFFF',
        'md-surface': '#FEF7FF',
        'md-on-surface': '#1D1B20',
        'md-on-surface-variant': '#49454F',
        'md-surface-container-lowest': '#FFFFFF',
        'md-surface-container-low': '#F7F2FA',
        'md-surface-container': '#F3EDF7',
        'md-surface-container-high': '#ECE6F0',
        'md-surface-container-highest': '#E6E0E9',
        'md-outline': '#79747E',
        'md-outline-variant': '#CAC4D0',

        // Material 3 dark scheme
        'md-dark-primary': '#A6C8FF',
        'md-dark-on-primary': '#003258',
        'md-dark-primary-container': '#00497D',
        'md-dark-on-primary-container': '#D3E3FD',
        'md-dark-secondary': '#9BCBFF',
        'md-dark-on-secondary': '#003355',
        'md-dark-secondary-container': '#004A77',
        'md-dark-on-secondary-container': '#CFE5FF',
        'md-dark-tertiary': '#D0BCFF',
        'md-dark-surface': '#131316',
        'md-dark-on-surface': '#E6E1E5',
        'md-dark-on-surface-variant': '#CAC4D0',
        'md-dark-surface-container-lowest': '#0E0E11',
        'md-dark-surface-container-low': '#1C1B1F',
        'md-dark-surface-container': '#211F26',
        'md-dark-surface-container-high': '#2B2930',
        'md-dark-surface-container-highest': '#36343B',
        'md-dark-outline': '#938F99',
        'md-dark-outline-variant': '#49454F',
      },
      fontFamily: {
        sans: ['Roboto', 'Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica Neue', 'Arial', 'sans-serif'],
        display: ['"Google Sans Display"', 'Roboto', 'system-ui', 'sans-serif'],
        mono: ['"Roboto Mono"', '"Fira Code"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      borderRadius: {
        // Material 3 shape scale
        'md-xs': '4px',
        'md-sm': '8px',
        'md-md': '12px',
        'md-lg': '16px',
        'md-xl': '28px',
      },
      boxShadow: {
        // Material 3 elevation
        'md-1': '0 1px 2px 0 rgba(0,0,0,0.30), 0 1px 3px 1px rgba(0,0,0,0.15)',
        'md-2': '0 1px 2px 0 rgba(0,0,0,0.30), 0 2px 6px 2px rgba(0,0,0,0.15)',
        'md-3': '0 1px 3px 0 rgba(0,0,0,0.30), 0 4px 8px 3px rgba(0,0,0,0.15)',
        'md-4': '0 2px 3px 0 rgba(0,0,0,0.30), 0 6px 10px 4px rgba(0,0,0,0.15)',
        'md-5': '0 4px 4px 0 rgba(0,0,0,0.30), 0 8px 12px 6px rgba(0,0,0,0.15)',
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': '#1D1B20',
            '--tw-prose-headings': '#1D1B20',
            '--tw-prose-links': '#0B57D0',
            'code::before': { content: '""' },
            'code::after': { content: '""' },
            code: {
              fontFamily: '"Roboto Mono", "Fira Code", monospace',
              fontWeight: '500',
              backgroundColor: '#F3EDF7',
              color: '#0B57D0',
              borderRadius: '4px',
              padding: '0.15em 0.4em',
              fontSize: '0.875em',
            },
            pre: {
              backgroundColor: '#F7F2FA',
              color: '#1D1B20',
              borderRadius: '12px',
              padding: '1rem',
              boxShadow: '0 1px 2px 0 rgba(0,0,0,0.30), 0 1px 3px 1px rgba(0,0,0,0.15)',
            },
            'pre code': {
              backgroundColor: 'transparent',
              color: 'inherit',
              padding: '0',
              fontSize: '0.875em',
              lineHeight: '1.7',
              fontFamily: '"Roboto Mono", "Fira Code", monospace',
            },
            blockquote: {
              borderLeftColor: '#0B57D0',
              color: '#49454F',
            },
          },
        },
        dark: {
          css: {
            '--tw-prose-body': '#E6E1E5',
            '--tw-prose-headings': '#E6E1E5',
            '--tw-prose-links': '#A6C8FF',
            color: '#E6E1E5',
            a: { color: '#A6C8FF' },
            strong: { color: '#E6E1E5' },
            h1: { color: '#E6E1E5' },
            h2: { color: '#E6E1E5' },
            h3: { color: '#E6E1E5' },
            h4: { color: '#E6E1E5' },
            h5: { color: '#E6E1E5' },
            h6: { color: '#E6E1E5' },
            code: { color: '#A6C8FF', backgroundColor: '#211F26' },
            'pre code': { color: '#E6E1E5', backgroundColor: 'transparent' },
            pre: { backgroundColor: '#1C1B1F', color: '#E6E1E5' },
            blockquote: { color: '#CAC4D0', borderLeftColor: '#A6C8FF' },
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
  darkMode: 'class',
}