/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './*.html',
    './blog/**/*.html',
    './presentations/**/*.html',
    './js/*.js',
    './_layouts/**/*.html',
    './_includes/**/*.html',
    './_posts/**/*.md',
  ],
  theme: {
    extend: {
      colors: {
        // Material 3 — light (only the tokens we actually use)
        'md-primary':                       '#0B57D0',
        'md-on-primary':                    '#FFFFFF',
        'md-primary-container':             '#D3E3FD',
        'md-on-primary-container':          '#001D35',
        'md-secondary-container':           '#CFE5FF',
        'md-on-secondary-container':        '#001D33',
        'md-tertiary-container':            '#EADDFF',
        'md-on-tertiary-container':         '#21005D',
        'md-surface':                       '#FEF7FF',
        'md-on-surface':                    '#1D1B20',
        'md-on-surface-variant':            '#49454F',
        'md-surface-container-lowest':      '#FFFFFF',
        'md-surface-container-low':         '#F7F2FA',
        'md-surface-container':             '#F3EDF7',
        'md-surface-container-high':        '#ECE6F0',
        'md-outline':                       '#79747E',
        'md-outline-variant':               '#CAC4D0',

        // Material 3 — dark
        'md-dark-primary':                  '#A6C8FF',
        'md-dark-on-primary':               '#003258',
        'md-dark-primary-container':        '#00497D',
        'md-dark-on-primary-container':     '#D3E3FD',
        'md-dark-secondary-container':      '#004A77',
        'md-dark-on-secondary-container':   '#CFE5FF',
        'md-dark-surface':                  '#131316',
        'md-dark-on-surface':               '#E6E1E5',
        'md-dark-on-surface-variant':       '#CAC4D0',
        'md-dark-surface-container-lowest': '#0E0E11',
        'md-dark-surface-container-low':    '#1C1B1F',
        'md-dark-surface-container':        '#211F26',
        'md-dark-surface-container-high':   '#2B2930',
        'md-dark-outline':                  '#938F99',
        'md-dark-outline-variant':          '#49454F',
      },
      fontFamily: {
        sans: ['Roboto', 'system-ui', '-apple-system', 'Segoe UI', 'Helvetica Neue', 'Arial', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      borderRadius: {
        'md-xs': '4px',
        'md-sm': '8px',
        'md-md': '12px',
        'md-lg': '16px',
        'md-xl': '28px',
      },
      boxShadow: {
        'md-1': '0 1px 2px 0 rgba(0,0,0,0.30), 0 1px 3px 1px rgba(0,0,0,0.15)',
        'md-2': '0 1px 2px 0 rgba(0,0,0,0.30), 0 2px 6px 2px rgba(0,0,0,0.15)',
        'md-3': '0 1px 3px 0 rgba(0,0,0,0.30), 0 4px 8px 3px rgba(0,0,0,0.15)',
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body':     '#1D1B20',
            '--tw-prose-headings': '#1D1B20',
            '--tw-prose-links':    '#0B57D0',
            'code::before': { content: '""' },
            'code::after':  { content: '""' },
            code: {
              backgroundColor: '#F3EDF7',
              color: '#0B57D0',
              borderRadius: '4px',
              padding: '0.15em 0.4em',
              fontWeight: '500',
              fontSize: '0.875em',
            },
            pre: {
              backgroundColor: '#F7F2FA',
              color: '#1D1B20',
              borderRadius: '12px',
              padding: '1.1rem 1.25rem',
              border: '1px solid #E6E0E9',
              boxShadow: 'none',
            },
            'pre code': {
              backgroundColor: 'transparent',
              color: 'inherit',
              padding: 0,
              fontSize: '0.875em',
              lineHeight: 1.7,
            },
            blockquote: {
              borderLeftColor: '#0B57D0',
              color: '#49454F',
              fontStyle: 'normal',
              fontWeight: '400',
              quotes: 'none',
            },
            'blockquote p:first-of-type::before': { content: 'none' },
            'blockquote p:last-of-type::after':   { content: 'none' },
            a: {
              fontWeight: '500',
              textDecoration: 'underline',
              textDecorationColor: 'rgba(11, 87, 208, 0.3)',
              textUnderlineOffset: '3px',
              transition: 'text-decoration-color 200ms ease',
            },
            'a:hover': { textDecorationColor: '#0B57D0' },
            h2: { marginTop: '2.5em', marginBottom: '0.8em' },
            h3: { marginTop: '2em',   marginBottom: '0.6em' },
            hr: { borderColor: '#E6E0E9', marginTop: '3em', marginBottom: '3em' },
            img: { borderRadius: '12px' },
          },
        },
        invert: {
          css: {
            '--tw-prose-body':         '#E6E1E5',
            '--tw-prose-headings':     '#E6E1E5',
            '--tw-prose-lead':         '#CAC4D0',
            '--tw-prose-links':        '#A6C8FF',
            '--tw-prose-bold':         '#E6E1E5',
            '--tw-prose-counters':     '#CAC4D0',
            '--tw-prose-bullets':      '#79747E',
            '--tw-prose-hr':           '#49454F',
            '--tw-prose-quotes':       '#CAC4D0',
            '--tw-prose-quote-borders':'#A6C8FF',
            '--tw-prose-captions':     '#CAC4D0',
            '--tw-prose-code':         '#A6C8FF',
            '--tw-prose-pre-code':     '#E6E1E5',
            '--tw-prose-pre-bg':       '#1C1B1F',
            '--tw-prose-th-borders':   '#49454F',
            '--tw-prose-td-borders':   '#36343B',
            code: { backgroundColor: '#2B2930', color: '#A6C8FF' },
            pre:  { backgroundColor: '#1C1B1F', borderColor: '#36343B' },
          },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
